[alias]
expand = ["bin", "cargo-expand"]
insta = ["bin", "cargo-insta"]
llvm-cov = ["bin", "cargo-llvm-cov"]

[build]
rustflags = ["-C", "target-feature=+crt-static"]

[env]
# Ideally we'd set more variables here, but the values we need to set vary by profile/platform.
# For now, the rest are set in the justfile.
#
# vcpkg-rs is disabled because the version on crates.io is really old and doesn't support
# vcpkg manifests / alternate installed directories.  Even the master branch also doesn't seem to
# have any way to correctly link with the vcpkg debug libraries in the debug/ subdirectories.
#
# https://github.com/mcgoo/vcpkg-rs/issues/41
# https://github.com/mcgoo/vcpkg-rs/issues/62
VCPKGRS_DISABLE = "1"
