[package]
name = "dv-toolbox-core"
authors.workspace = true
categories.workspace = true
description = "Library for working with and restoring videos in Digital Video (DV) format."
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true
